export const FAKE_PRODUCT_LIST = {
  products: [
    {
      id: 1,
      name: "iPhone 13 Pro Max",
      price: 28990000,
      type: "iphone",
      image: require("./images/iPhone-13-pro-max.png"),
    },
    {
      id: 2,
      name: "iPhone 13 Pro",
      price: 26990000,
      type: "iphone",
      image: require("./images/iPhone-13-pro.png"),
    },
    {
      id: 3,
      name: "iPhone 13",
      price: 19990000,
      type: "iphone",
      image: require("./images/iPhone-13.png"),
    },
    {
      id: 4,
      name: "iPhone 13 Mini",
      price: 18590000,
      type: "iphone",
      image: require("./images/iPhone-13-mini.png"),
    },
    {
      id: 5,
      name: "iPhone 12",
      price: 15790000,
      type: "iphone",
      image: require("./images/iPhone-12.png"),
    },
    {
      id: 6,
      name: "iPhone 12 Mini",
      price: 14950000,
      type: "iphone",
      image: require("./images/iPhone-12-mini.png"),
    },
    {
      id: 7,
      name: "iPhone 11",
      price: 11390000,
      type: "iphone",
      image: require("./images/iPhone-11.png"),
    },
    {
      id: 8,
      name: "iPhone SE 2022",
      price: 10990000,
      type: "iphone",
      image: require("./images/iPhone-SE-2022.png"),
    },
    {
      id: 9,
      name: "iPad Pro 12.9 inch",
      price: 24490000,
      type: "ipad",
      image: require("./images/iPad-pro-12.9inch.png"),
    },
    {
      id: 10,
      name: "iPad Pro 11 inch",
      price: 19890000,
      type: "ipad",
      image: require("./images/iPad-pro-11inch.png"),
    },
    {
      id: 11,
      name: "iPad Gen 9",
      price: 8990000,
      type: "ipad",
      image: require("./images/iPad-gen-9.png"),
    },
    {
      id: 12,
      name: "iPad Mini 6",
      price: 13290000,
      type: "ipad",
      image: require("./images/iPad-mini-6.png"),
    },
    {
      id: 13,
      name: "iPad Air 5",
      price: 15490000,
      type: "ipad",
      image: require("./images/iPad-air-5.png"),
    },
    {
      id: 14,
      name: "iPad Air 4",
      price: 13990000,
      type: "ipad",
      image: require("./images/iPad-air-4.png"),
    },
    {
      id: 15,
      name: "MacBook Pro 16 M1 Max",
      price: 89950000,
      type: "mac",
      image: require("./images/macBook-pro-16-m1-max.png"),
    },
    {
      id: 16,
      name: "MacBook Pro 16 M1",
      price: 58990000,
      type: "mac",
      image: require("./images/macBook-pro-16-m1.png"),
    },
    {
      id: 17,
      name: "MacBook Pro 14 M1 Max",
      price: 71990000,
      type: "mac",
      image: require("./images/macBook-pro-14-m1-max.png"),
    },
    {
      id: 18,
      name: "MacBook Pro 14 M1",
      price: 57450000,
      type: "mac",
      image: require("./images/macBook-pro-14-m1.png"),
    },
    {
      id: 19,
      name: "MacBook Pro 13 M2",
      price: 35990000,
      type: "mac",
      image: require("./images/macBook-pro-13-m2.png"),
    },
    {
      id: 20,
      name: "MacBook Pro M1",
      price: 30250000,
      type: "mac",
      image: require("./images/macBook-pro-m1.png"),
    },
    {
      id: 21,
      name: "MacBook Air M2",
      price: 32990000,
      type: "mac",
      image: require("./images/macBook-air-m2.png"),
    },
    {
      id: 22,
      name: "MacBook Air M1",
      price: 23290000,
      type: "mac",
      image: require("./images/macBook-air-m1.png"),
    },
    {
      id: 23,
      name: "iMac M1 2021 24 inch",
      price: 38990000,
      type: "mac",
      image: require("./images/iMac-m1-2021-24inch.png"),
    },
    {
      id: 24,
      name: "iMac 2020 27 inch",
      price: 38950000,
      type: "mac",
      image: require("./images/iMac-2020-27inch.png"),
    },
    {
      id: 25,
      name: "iMac 2020 21.5 inch",
      price: 24550000,
      type: "mac",
      image: require("./images/iMac-2020-21.5inch.png"),
    },
    {
      id: 26,
      name: "Apple Watch Series 7 Thép",
      price: 17990000,
      type: "apple-watch",
      image: require("./images/apple-watch-sr7-thep.png"),
    },
    {
      id: 27,
      name: "Apple Watch Series 7 Nhôm",
      price: 9590000,
      type: "apple-watch",
      image: require("./images/apple-watch-sr7-nhom.png"),
    },
    {
      id: 28,
      name: "Apple Watch Series 6 Thép",
      price: 14990000,
      type: "apple-watch",
      image: require("./images/apple-watch-sr6-thep.png"),
    },
    {
      id: 29,
      name: "Apple Watch Series 6 Nhôm",
      price: 7490000,
      type: "apple-watch",
      image: require("./images/apple-watch-sr6-nhom.png"),
    },
    {
      id: 30,
      name: "Apple Watch SE",
      price: 6890000,
      type: "apple-watch",
      image: require("./images/apple-watch-se.png"),
    },
    {
      id: 31,
      name: "Apple Watch Series 3",
      price: 4790000,
      type: "apple-watch",
      image: require("./images/apple-watch-sr3.png"),
    },
    {
      id: 32,
      name: "AirPods Pro",
      price: 4590000,
      type: "am-thanh",
      image: require("./images/airPods-pro.png"),
    },
    {
      id: 33,
      name: "AirPods 3",
      price: 4450000,
      type: "am-thanh",
      image: require("./images/airPods-3.png"),
    },
    {
      id: 34,
      name: "AirPods 2",
      price: 2690000,
      type: "am-thanh",
      image: require("./images/airPods-2.png"),
    },
    {
      id: 35,
      name: "Beats Studio3 Wireless Headphones",
      price: 5990000,
      type: "am-thanh",
      image: require("./images/beats-studio3-wireless-headphones.png"),
    },
    {
      id: 36,
      name: "Beats Solo3 Wireless Headphones",
      price: 4100000,
      type: "am-thanh",
      image: require("./images/beats-solo3-wireless-headphones.png"),
    },
    {
      id: 37,
      name: "EarPods with Lightning",
      price: 590000,
      type: "am-thanh",
      image: require("./images/earPods-lightning.png"),
    },
    {
      id: 38,
      name: "EarPods with Remote",
      price: 350000,
      type: "am-thanh",
      image: require("./images/earPods-remote.png"),
    },
    {
      id: 39,
      name: "Loa Beats Pill + Speaker",
      price: 4990000,
      type: "am-thanh",
      image: require("./images/loa-beats-pill.png"),
    },
    {
      id: 40,
      name: "Loa Harman Kardon Citation 100",
      price: 7800000,
      type: "am-thanh",
      image: require("./images/loa-harman-kardon-citation.png"),
    },
    {
      id: 41,
      name: "Loa Harman Kardon Onyx Studio 5",
      price: 3950000,
      type: "am-thanh",
      image: require("./images/loa-harman-kardon-onyx-studio.png"),
    },
    {
      id: 42,
      name: "Loa JBL CHARGE5",
      price: 3990000,
      type: "am-thanh",
      image: require("./images/loa-JBL-charge.png"),
    },
    {
      id: 43,
      name: "Loa JBL PartyBox710",
      price: 19900000,
      type: "am-thanh",
      image: require("./images/loa-JBL-partyBox.png"),
    },
    {
      id: 44,
      name: "Cáp USB-C to Lightning Cable",
      price: 590000,
      type: "phu-kien",
      image: require("./images/cap-USB-C-to-lightning.png"),
    },
    {
      id: 45,
      name: "Bộ sạc không dây Hyperjuice Magnetic 2 in 1",
      price: 1190000,
      type: "phu-kien",
      image: require("./images/sac-khong-day.png"),
    },
    {
      id: 46,
      name: "RAVPower Pin Sạc Dự Phòng 10000mAh",
      price: 350000,
      type: "phu-kien",
      image: require("./images/sac-du-phong.png"),
    },
    {
      id: 47,
      name: "Pencil 2",
      price: 3290000,
      type: "phu-kien",
      image: require("./images/pencil-2.png"),
    },
    {
      id: 48,
      name: "Pencil 1",
      price: 2490000,
      type: "phu-kien",
      image: require("./images/pencil-1.png"),
    },
    {
      id: 49,
      name: "Magic Keyboard",
      price: 2450000,
      type: "phu-kien",
      image: require("./images/ban-phim.jpg"),
    },
    {
      id: 50,
      name: "Magic Mouse",
      price: 2550000,
      type: "phu-kien",
      image: require("./images/chuot.jpg"),
    },
    {
      id: 51,
      name: "Balo TOMTOC Premium Urban Business",
      price: 1350000,
      type: "phu-kien",
      image: require("./images/balo.jpg"),
    },
    {
      id: 52,
      name: "Túi chống sốc SEINE SCENE ORLEANS 15.6 inch",
      price: 750000,
      type: "phu-kien",
      image: require("./images/tui-chong-soc-15.6inch.jpg"),
    },
    {
      id: 53,
      name: "Bao da Ducis iPad Mini 6 8.3 inch",
      price: 300000,
      type: "phu-kien",
      image: require("./images/bao-da-iPad-mini-6-8.3inch.jpg"),
    },
    {
      id: 54,
      name: "Ốp lưng Likgus iPhone 13 Pro Max clear",
      price: 150000,
      type: "phu-kien",
      image: require("./images/op-iphone-13-pro-max.png"),
    },
    {
      id: 55,
      name: "Ốp Rockrose Veill II Airpod 2",
      price: 170000,
      type: "phu-kien",
      image: require("./images/op-airpod-2.png"),
    },
    {
      id: 56,
      name: "Dây đeo Watch 40mm Sport Band – Regular",
      price: 1290000,
      type: "phu-kien",
      image: require("./images/day-deo-apple-watch-den.jpg"),
    },
    {
      id: 57,
      name: "Dây đeo Watch 40mm Nike Sport Loop",
      price: 1290000,
      type: "phu-kien",
      image: require("./images/day-deo-apple-watch-trang.jpg"),
    },
    {
      id: 58,
      name: "Miếng dán cường lực Supitec iPhone 13 Pro Max",
      price: 200000,
      type: "phu-kien",
      image: require("./images/cuong-luc.png"),
    },
  ],
};
